### ISSUE TITLE
How to access messages from a subscriber?

### ISSUE THREAD

**Issue by matejpoliacek** [gnoliyil/ROSBridgePlugin#1]
I extended the code to subscribe to more topics - how can I access the data received from ROS in UE?

**Comment by gnoliyil** [comment]
1. Create a `ROSBridgeSubscriber`'s subclass and implement these two functions: 
  -  `TSharedPtr<FROSBridgeMsg> ParseMessage(TSharedPtr<FJsonObject> JsonObject) const;`
  - `void CallBack(TSharedPtr<FROSBridgeMsg> msg) const;`
  See this example: https://github.com/gnoliyil/URoboSim/blob/RI/ROSBridgeTest/Source/ROSBridgeTest/ROSStringSubscriber.h
2. In Actor, define a Handler pointer and a Subscriber pointer: 
```cpp
UCLASS()
class ROSBRIDGETEST_API AROSBridgeTestGameModeBase : public AGameModeBase
{
    TSharedPtr<FROSBridgeHandler> Handler;
    TSharedPtr<FROSStringSubScriber> Subscriber;
    ...
}
```
3. In Actor, implement `BeginPlay()`, `Tick()` and `EndPlay()` functions. See the following example:
```
void AROSBridgeTestGameModeBase::BeginPlay()
{
    Super::BeginPlay();

    // Set websocket server address to ws://127.0.0.1:9001
    Handler = MakeShareable<FROSBridgeHandler>(new FROSBridgeHandler(TEXT("127.0.0.1"), 9001));
    UE_LOG(LogTemp, Log, TEXT("Handler Created. "));

    // Add subscriber for /chatter topic
    Subscriber = MakeShareable<FROSStringSubScriber>(new FROSStringSubScriber(TEXT("/chatter")));
    Handler->AddSubscriber(Subscriber);
    UE_LOG(LogTemp, Log, TEXT("Added chatter subscriber. "));

    // Connect to ROSBridge Websocket server.
    Handler->Connect();
    UE_LOG(LogTemp, Log, TEXT("Connected to WebSocket server. "));
}

void AROSBridgeTestGameModeBase::Tick(float DeltaSeconds)
{
    Super::Tick(DeltaSeconds);
    Handler->Render();
}


void AROSBridgeTestGameModeBase::Logout(AController *Exiting) // Or run Disconnect() in EndPlay() method
{
    Handler->Disconnect();
    AGameModeBase::Logout(Exiting);
}
```
See this project (https://github.com/gnoliyil/URoboSim/tree/RI/ROSBridgeTest/Source/ROSBridgeTest) for example.

**Comment by gnoliyil** [comment]
@matejpoliacek Please do not forget to add `Json, JsonUtilities, ROSBridgePlugin` in your Build.cs configuration file. 
This plugin will be renamed to "UROSBridge" and will be moved to [this](https://github.com/gnoliyil/UROSBridge) repository. Future bugfixes will be pushed there.

**Comment by matejpoliacek** [comment]
@gnoliyil Thank you for the guide and for the heads up
